import Foundation
import AppKit

enum LaunchAgentInstaller {
    static let label = "com.user.claude-usage-toolbar"

    static func installIfNeeded() {
        let fm = FileManager.default
        let home = fm.homeDirectoryForCurrentUser
        let agentsDir = home.appendingPathComponent("Library/LaunchAgents", isDirectory: true)
        let plistURL = agentsDir.appendingPathComponent("\(label).plist")
        let scriptURL = home
            .appendingPathComponent("Library/Application Support/ClaudeUsageToolbar", isDirectory: true)
            .appendingPathComponent("launch.sh")

        do {
            try fm.createDirectory(at: agentsDir, withIntermediateDirectories: true)
            try fm.createDirectory(at: scriptURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        } catch {
            NSLog("[ClaudeUsageToolbar] LaunchAgent dirs: %@", "\(error)")
            return
        }

        let appPath = Bundle.main.bundleURL.path
        let scriptBody = """
        #!/bin/bash
        # Generated by ClaudeUsageToolbar; safe to delete.
        pgrep -xq Claude || exit 0
        pgrep -xq ClaudeUsageToolbar && exit 0
        open -gj "\(appPath)"
        """

        let plistBody = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>\(label)</string>
            <key>ProgramArguments</key>
            <array>
                <string>/bin/bash</string>
                <string>\(scriptURL.path)</string>
            </array>
            <key>StartInterval</key>
            <integer>5</integer>
            <key>RunAtLoad</key>
            <true/>
            <key>StandardOutPath</key>
            <string>/tmp/claude-usage-toolbar-launchagent.log</string>
            <key>StandardErrorPath</key>
            <string>/tmp/claude-usage-toolbar-launchagent.log</string>
        </dict>
        </plist>
        """

        let scriptChanged = writeIfChanged(content: scriptBody, to: scriptURL)
        if scriptChanged {
            _ = try? fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)
            NSLog("[ClaudeUsageToolbar] LaunchAgent: script written to %@", scriptURL.path)
        } else {
            NSLog("[ClaudeUsageToolbar] LaunchAgent: script unchanged")
        }
        let plistChanged = writeIfChanged(content: plistBody, to: plistURL)

        if plistChanged {
            NSLog("[ClaudeUsageToolbar] LaunchAgent: plist changed, re-bootstrapping")
            let uid = getuid()
            let bootout = runShell("/bin/launchctl", ["bootout", "gui/\(uid)/\(label)"])
            NSLog("[ClaudeUsageToolbar] LaunchAgent: bootout exit=%d", bootout)
            let bootstrap = runShell("/bin/launchctl", ["bootstrap", "gui/\(uid)", plistURL.path])
            NSLog("[ClaudeUsageToolbar] LaunchAgent: bootstrap exit=%d", bootstrap)
        } else {
            NSLog("[ClaudeUsageToolbar] LaunchAgent: plist unchanged, no re-bootstrap needed")
        }
    }

    private static func writeIfChanged(content: String, to url: URL) -> Bool {
        let new = content.data(using: .utf8) ?? Data()
        if let existing = try? Data(contentsOf: url), existing == new { return false }
        do {
            try new.write(to: url, options: .atomic)
            return true
        } catch {
            NSLog("[ClaudeUsageToolbar] write %@: %@", url.path, "\(error)")
            return false
        }
    }

    @discardableResult
    private static func runShell(_ launchPath: String, _ args: [String]) -> Int32 {
        let p = Process()
        p.launchPath = launchPath
        p.arguments = args
        let outPipe = Pipe()
        p.standardOutput = outPipe
        p.standardError = outPipe
        do {
            try p.run()
            p.waitUntilExit()
            return p.terminationStatus
        } catch {
            return -1
        }
    }
}
